name: pack

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  pack:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: Setup folders
        run: |
          cd ${{ github.workspace }}
          ls
          sudo mkdir -p /trainSystemPacked/bin/x64/plugins/cyber_engine_tweaks/mods/trainSystem/
          sudo mkdir -p /trainSystemPacked/bin/x64/plugins/cyber_engine_tweaks/mods/nativeSettings/
          sudo mkdir -p /trainSystemPacked/archive/pc/mod/
          ls
