name: pack

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  pack:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: Setup folders
        run: |
          cd ${{ github.workspace }}
          mkdir /bin/x64/plugins/cyber_engine_tweaks/mods/trainSystem
          mkdir /bin/x64/plugins/cyber_engine_tweaks/mods/nativeSettings
          mkdir /bin/x64/plugins/cyber_engine_tweaks/mods/trainSystem
          mkdir /archive/pc/mod
      - name: Copy files
        run: |
          cp -r /modules /bin/x64/plugins/cyber_engine_tweaks/mods/trainSystem
          cp -r /debug /bin/x64/plugins/cyber_engine_tweaks/mods/trainSystem
          cp -r /data /bin/x64/plugins/cyber_engine_tweaks/mods/trainSystem
          cp -r /CPStyling /bin/x64/plugins/cyber_engine_tweaks/mods/trainSystem
          cp -r /init.lua /bin/x64/plugins/cyber_engine_tweaks/mods/trainSystem
          cp -r /trainSystem.archive /archive/pc/mod
          ls
