name: pack

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  pack:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup folders
        run: |
          cd ${{ github.workspace }}
          sudo mkdir -p /trainSystemPacked/bin/x64/plugins/cyber_engine_tweaks/mods/trainSystem/
          sudo mkdir -p /trainSystemPacked/bin/x64/plugins/cyber_engine_tweaks/mods/nativeSettings/
          sudo mkdir -p /trainSystemPacked/archive/pc/mod/
      - name: Copy files
        run: |
          sudo cp -r modules /trainSystemPacked/bin/x64/plugins/cyber_engine_tweaks/mods/trainSystem/
          sudo cp -r debug /trainSystemPacked/bin/x64/plugins/cyber_engine_tweaks/mods/trainSystem/
          sudo cp -r data /trainSystemPacked/bin/x64/plugins/cyber_engine_tweaks/mods/trainSystem/
          sudo cp -r CPStyling /trainSystemPacked/bin/x64/plugins/cyber_engine_tweaks/mods/trainSystem/
          sudo cp -r init.lua /trainSystemPacked/bin/x64/plugins/cyber_engine_tweaks/mods/trainSystem/
          sudo cp -r trainSystem.archive /trainSystemPacked/archive/pc/mod/
          ls trainSystemPacked
      - name: Upload zip
        uses: actions/upload-artifact@v2
        with:
            name: package
            path: trainSystemPacked